# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3781900c76303f9aea72566c9f19db0392f48e89f8c0f3dd5c9d40624e4aa83975ede4b2efa2f87e0d91609c0a383717710361e41f9787cdfa7af544b6188d2

test:
  secret_key_base: 96750a0a23e31f5d07945a89ca69f2da5ec90ada37c9e27df7cf63ae2c466ac73498d7172d5170209b2a3c09f88e4effae792c24113a04d0e0875a2119da5acf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
